api_scgas:
  scgas:
    base_url: "https://scada.scgas.com.br"
    
    authentication:
      auth_url: "/api/Auth/Token"
      username: "${scgas_api.username}"
      password: "${scgas_api.password}"
    
    endpoints:
      history_measurement: "/api/Variable/History/Measurement"
      variable_status: "/api/Variable/Status"
    
    # Body padrão para consulta de medições
    measurement_request_body:
      idIntegracao: "VRTA-CLT-41-023-0001"
      tagList: ["HistTotal"]
      from: "2025-01-01T00:00:00.000-03:00"
      to: "2025-08-07T00:00:00.000-03:00"
      groupBy: "h"
      calcBy: "val"
    
    data_headers:
      "Content-Type": "application/json"
      "Accept": "*/*"
    
    auth_headers:
      "Content-Type": "application/json"
      "Accept": "*/*"
    
    timeout: 30
    retry_attempts: 3
    rate_limit_per_minute: 60
    rate_limit_per_hour: 3600
    backoff_factor: 2

  data_processing:
    batch_size: 1000
    max_retries: 3
    retry_delay_seconds: 5

  logging:
    log_api_calls: true
    log_response_times: true
    log_error_details: true
